import CryptoKit
import Foundation

enum ClipboardHistoryKind: String, Codable, Sendable {
    case text
    case image
}

struct ClipboardHistoryRecord: Codable, Equatable, Sendable, Identifiable {
    var id: UUID
    var kind: ClipboardHistoryKind
    var createdAt: Date
    var lastCopiedAt: Date
    var isFavorite: Bool
    var favoritedAt: Date?
    var contentHash: String
    var text: String?
    var assetPath: String?
}

struct ClipboardHistoryDatabase: Codable, Equatable, Sendable {
    var schemaVersion: Int
    var items: [ClipboardHistoryRecord]

    static let currentSchemaVersion = 1

    init(
        schemaVersion: Int = currentSchemaVersion,
        items: [ClipboardHistoryRecord] = []
    ) {
        self.schemaVersion = schemaVersion
        self.items = items
    }
}

enum ClipboardHistoryPolicy {
    static let maximumRecentNonFavorites = 100
    static let maximumStoredImageBytes = 20 * 1024 * 1024
    static let pollInterval: TimeInterval = 0.5
}

enum ClipboardHistoryHasher {
    static func hash(text: String) -> String {
        sha256Hex(Data(text.utf8))
    }

    static func hash(png: Data) -> String {
        sha256Hex(png)
    }

    static func sha256Hex(_ data: Data) -> String {
        SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
    }
}

enum ClipboardHistorySearch {
    static func matches(_ record: ClipboardHistoryRecord, query: String) -> Bool {
        let needle = query.trimmingCharacters(in: .whitespacesAndNewlines)
        if needle.isEmpty { return true }
        switch record.kind {
        case .image:
            return false
        case .text:
            return (record.text ?? "").range(
                of: needle,
                options: [.caseInsensitive, .diacriticInsensitive]
            ) != nil
        }
    }

    static func recent(_ records: [ClipboardHistoryRecord], query: String) -> [ClipboardHistoryRecord] {
        records
            .sorted { $0.lastCopiedAt > $1.lastCopiedAt }
            .filter { matches($0, query: query) }
    }

    static func favorites(_ records: [ClipboardHistoryRecord], query: String) -> [ClipboardHistoryRecord] {
        records
            .filter(\.isFavorite)
            .sorted { ($0.favoritedAt ?? .distantPast) > ($1.favoritedAt ?? .distantPast) }
            .filter { matches($0, query: query) }
    }
}

enum ClipboardHistoryRetention {
    static func idsToEvict(
        from records: [ClipboardHistoryRecord],
        limit: Int = ClipboardHistoryPolicy.maximumRecentNonFavorites
    ) -> [UUID] {
        let nonFavorites = records
            .filter { !$0.isFavorite }
            .sorted { lhs, rhs in
                if lhs.lastCopiedAt != rhs.lastCopiedAt {
                    return lhs.lastCopiedAt < rhs.lastCopiedAt
                }
                return lhs.createdAt < rhs.createdAt
            }
        let overflow = nonFavorites.count - limit
        guard overflow > 0 else { return [] }
        return Array(nonFavorites.prefix(overflow).map(\.id))
    }
}

enum ClipboardHistoryPreview {
    static func lines(from text: String, limit: Int = 72) -> (String, String?) {
        let parts = text
            .split(whereSeparator: \.isNewline)
            .map { $0.trimmingCharacters(in: .whitespaces) }
            .filter { !$0.isEmpty }
        let first = truncate(parts.first ?? text, limit: limit)
        let second = parts.dropFirst().first.map { truncate($0, limit: limit) }
        return (first, second)
    }

    static func truncate(_ text: String, limit: Int) -> String {
        guard text.count > limit else { return text }
        return String(text.prefix(limit)) + "…"
    }
}

enum ClipboardPrivacyMarkers {
    static let typeStrings = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType"
    ]

    static func shouldSkip(typeStrings: [String]) -> Bool {
        let present = Set(typeStrings)
        return Self.typeStrings.contains { present.contains($0) }
    }
}

enum ClipboardHistoryCopy {
    static let windowTitle = "剪贴板"
    static let searchPrompt = "搜索剪贴板…"
    static let recentTab = "最近"
    static let favoriteTab = "收藏"
    static let recording = "正在记录"
    static let enableTitle = "保存最近复制的内容"
    static let enableBody = "Glance 可以在本机记录你之后复制的文字和图片，方便搜索、收藏和再次使用。\n\n内容不会上传。"
    static let enableAction = "开始记录"
    static let emptyRecentTitle = "还没有剪贴板记录"
    static let emptyRecentDetail = "复制一些文字或图片后，它们会出现在这里。"
    static let emptyFavoritesTitle = "还没有收藏"
    static let emptyFavoritesDetail = "把常用内容标记为 ★，之后可以随时调用。"
    static let emptySearch = "没有找到匹配的内容"
    static let futureSchema = "此版本无法读取剪贴板历史"
    static let reuseHint = "↩ 复制"
    static let panelHint = "⌘↩ 创建面板"
    static let closeHint = "Esc 关闭"
    static let favoriteLabel = "收藏"
    static let unfavoriteLabel = "取消收藏"
    static let deleteLabel = "删除"
    static let saveAsSnippet = "保存为片段…"
}

enum ClipboardHistoryLoadOutcome: Equatable {
    case missing
    case loaded
    case recoveredFromCorruption
    case unsupportedFutureSchema(Int)
    case unavailable
}
